services:
  bookshelf_db:
    container_name: bookshelf_db
    image: postgres
    working_dir: /usr/src/app
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./volumes/schema.sql:/docker-entrypoint-initdb.d/schema.sql
